name: rdd_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.26.4
  - pandas
  - pyyaml
  - tqdm
  - pillow
  - tensorboard
  - pip:
      - "numpy<2.0"
      - torchmetrics
      - torch==2.0.1
      - torchvision==0.15.2
      - pycocotools==2.0.7
      - opencv-python
      - datasets
      - torchinfo