dataset_params:
  root_path: 'dataset/RDD2022'
  countries: ['China_Drone', 'China_MotorBike', 'Czech', 'India', 'Japan', 'Norway', 'United_States']
  class_mapping:
    'BG': 0
    'D00': 1 # Pęknięcie podłuzne
    'D10': 2 # Pęknięcie poprzeczne
    'D20': 3 # Pęknięcie siatkowe
    'D40': 4 # Wybój
  num_classes : 5

train_params:
  task_name: 'results'
  seed : 1111
  train_val_ratio : 0.8
  batch_size : 2
  acc_steps : 1
  num_epochs: 1
  lr_steps : [12, 16]
  lr: 0.001
  early_stopping_patience: 5
  iou_threshold_map: 0.5
  ckpt_name: 'faster_rcnn_rdd.pth'

validation_params:
  max_val_images: 200
  batch_size: 1
  score_threshold: 0.15