dataset_params:
  root_path: 'dataset'
  countries: ['China_Drone', 'Czech', 'India', 'Japan', 'Norway', 'United_States']
  class_mapping:
    'background': 0
    'PPD': 1 # Pęknięcie podłuzne
    'PPP': 2 # Pęknięcie poprzeczne
    'PS': 3 # Pęknięcie siatkowe
    'WY': 4 # Wybój
  num_classes : 5

model_params:
  im_channels : 3
  aspect_ratios: [0.5, 1, 2]
  scales: [128, 256, 512]
  min_im_size : 600
  max_im_size : 1000
  backbone_out_channels : 2048 # Dla ResNet50, dla VGG16 512
  fc_inner_dim : 1024
  rpn_bg_threshold : 0.3
  rpn_fg_threshold : 0.7
  rpn_nms_threshold : 0.7
  rpn_train_prenms_topk : 12000
  rpn_test_prenms_topk : 6000
  rpn_train_topk : 2000
  rpn_test_topk : 300
  rpn_batch_size : 256
  rpn_pos_fraction : 0.5
  roi_iou_threshold : 0.5
  roi_low_bg_iou : 0.0 
  roi_pool_size : 7
  roi_nms_threshold : 0.3
  roi_topk_detections : 100
  roi_score_threshold : 0.05
  roi_batch_size : 128
  roi_pos_fraction : 0.25
  backbone_out_channels : 512
  roi_pool_size : 7

train_params:
  task_name: 'rdd_detection'
  seed : 1111
  acc_steps : 1 
  num_epochs: 20
  lr_steps : [12, 16]
  lr: 0.001
  early_stopping_patience: 5
  iou_threshold_map: 0.5
  ckpt_name: 'faster_rcnn_rdd.pth'